/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    java
    id("org.springframework.boot") version "3.5.7"
	id("io.spring.dependency-management") version "1.1.7"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.1")

    // JAXB
    implementation("org.glassfish.jaxb:jaxb-runtime:4.0.6") // XML marshalling (runtime)
    implementation("com.sun.xml.bind:jaxb-xjc:4.0.6"){ // XSD → Java code generation
    exclude(group = "com.sun.xml.bind", module = "jaxb-core")
}       

    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")

    testImplementation("org.junit.jupiter:junit-jupiter:5.11.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Java toolchain
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
        sourceSets["main"].java.srcDirs(
        "src/main/java",
        layout.buildDirectory.dir("generated/src/main/java") // if using XJC
    )
}

// Main class
application {
    mainClass.set("de.digitalservice.App")
}

val xjcGenerate = tasks.register<JavaExec>("xjcGenerate") {
    group = "build"
    description = "Generate Java classes from all XSD files in src/main/resources/xjustiz"

    // Temporarily print classpath
    doFirst {
        println("=== XJC classpath contents ===")
        classpath.files.forEach { println("  ${it.name}") }
    }

    mainClass.set("com.sun.tools.xjc.XJCFacade")  
    
    classpath = configurations.runtimeClasspath.get()

    val xsdDir = file("src/main/resources/xjustiz")
    val outputDir = layout.buildDirectory.dir("generated/src/main/java").get().asFile

    inputs.files(xsdDir.listFiles()?.filter { it.extension == "xsd" } ?: listOf<File>())
    outputs.dir(outputDir)

    doFirst {
        outputDir.mkdirs()

        val xsdFiles = xsdDir.listFiles { file -> file.extension == "xsd" }
            ?.map { it.absolutePath } ?: emptyList()

        if (xsdFiles.isEmpty()) {
            throw GradleException("No XSD files found in ${xsdDir.absolutePath}")
        }

        args = listOf("-d", outputDir.absolutePath) + xsdFiles
    }
}

// Add generated sources to Java compilation
java {
    sourceSets["main"].java.srcDir(layout.buildDirectory.dir("generated/src/main/java"))
}

// Make compilation depend on XJC generation
tasks.named("compileJava") {
    dependsOn(xjcGenerate)
}

// JUnit configuration
tasks.named<Test>("test") {
    useJUnitPlatform()
}


