/*
 * This source file was generated by the Gradle 'init' task
 */
package de.digitalservice;

import org.junit.jupiter.api.Test;

import de.digitalservice.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should do something");
    }
}
